### ISSUE TITLE
Laggy sentry upgrade animation

### ISSUE THREAD

**Issue by benscobie** [tf2configs/tf2configs#2]
Since using the max quality configuration the sentry upgrade animations have been consistently jerky(low FPS animation), which option could cause this? My friend is also having the same problem using the same configuration.

**Comment by cdown** [comment]
I believe, although I am not sure, that this is an inherent property of DirectX 8. I will investigate further.

**Comment by benscobie** [comment]
DirectX 8? I'm using -dxlevel 98

**Comment by cdown** [comment]
Ah, okay. In which case yes, this is not intentional. I will look into it when I have time.

**Comment by cdown** [comment]
Close, unsupported.
